### ISSUE TITLE
Task List First Version

### ISSUE THREAD

**Issue by lab-one** [IdeaX/idea-engine#21]
Sprites.

    Simple sprite                                                 COMPLETE
    Animated Sprite.                                              NOT IMPLEMENTED
    Collision mask sprite or rectangle or ellipse.                NOT IMPLEMENTED
    Draw Event for object, for creating custom sprites or texts   NOT IMPLEMENTED

Object

    Keyboard Events.                                              HALF COMPLETE
    Mouse Click and move                                          HALF COMPLETE
    Collision Event.                                              NOT IMPLEMENTED
    Animation End Event.                                          ТOT IMPLEMENTED
    Simplified user defined Events                                NOT IMPLEMENTED 
    private step event, user cant redefine                        HALF COMPLETE
            (for speed control, for example)   
    user defined OnStep Event,                                    HALF COMPLETE   second thread
    Object can switch scenes                                      NOT IMPLEMENTED
    Object create another object on current scene.                HALF COMPLETE
    object can switch cameras                                     NOT IMPLEMENTED
    Depth of object for control drawing stack                     NOT IMPLEMENTED

Camera.

    Movable by object                                             NOT IMPLEMENTED
    switch between cameras on scene                               TEST NEEDED
    Infinity camera Zoom                                          NOT IMPLEMENTED

Engine

    Two threads, main for drawing, second for StepEvents          NOT IMPLEMENTED

File system

    Make/read config file                                         COMPLETE?
    Make read save files                                          NOT IMPLEMENTED

**Comment by crioto** [comment]
#22 
#23 
#24 
#25 
#26 
#27 
#28 
#29 
#30 
#31 
#32 
#33 
#34 
#35 
#36 
#37 
#38 
#39 
#40 
#41
