### ISSUE TITLE
Implement init parameters

### ISSUE THREAD

**Issue by crioto** [IdeaX/idea-engine#5]
Graphics parameters should be kept in configuration file

**Comment by lab-one** [comment]
Logic of game options depends from game-developer and platform.
For now we can control resolution with cameras and I think it will be convenient if we provide for developer easy way to read/write text files from game sandbox (or file-system).
So the can store resolution in "configuration.ini" file, for example

    Camera camera;
    camera.resolution = IdeaEngine::readConfig("resolution");

and in options menu

    Object resolutionController;
    bla bla bla
    IdeaEngine::setConfig(resolutionController.getValue);

**Comment by crioto** [comment]
In master
